[package]
name = "enter"
version = "0.0.1"
authors = ["huangjj27 <huangjj.27@qq.com>"]
description = "a simple crate to solve the CR/LF/CRLF problem from one line input on different OS"
license = "MIT/Apache-2.0"

[dependencies]
