[package]
name = "enter"
version = "1.0.0"
authors = ["huangjj27 <huangjj.27@qq.com>"]
repository = "https://github.com/huangjj27/enter"
description = "The only thing the crate doing is to privide constant CR, LF, CRLF and ENTER."
license = "MIT/Apache-2.0"
readme = "README.md"
